jobs:
  one:
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
          key: v1-dependencies-
  two:
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
