jobs:
  build:
    branches:
      only: master
        docker:
          - image: circleci/node:11.6.0
        steps:
          - checkout
          - run:
              name: Install dependencies
              command: npm install

      two:
        docker:
          - image: circleci/node:11.6.0
        steps:
          - checkout
          - run: echo "A more familiar hi"
          - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
